language: node_js

node_js:
- 4
- stable

before_install:
- npm install -g npm@5

script:
- npm run lint
- npm run test

after_script:
- npx codecov

cache:
  directories:
  - node_modules

matrix:
  fast_finish: true
